- id: '1532694621417'
  alias: Pumpe ein
  trigger:
  - entity_id: switch.r1
    platform: state
    to: 'on'
  - entity_id: switch.r2
    platform: state
    to: 'on'
  - entity_id: switch.r3
    platform: state
    to: 'on'
  - entity_id: switch.r4
    platform: state
    to: 'on'
  - entity_id: switch.r5
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.relais_pumpe
    service: switch.turn_on
- id: '1536869213637'
  alias: Pumpe aus
  trigger:
  - entity_id: switch.r1
    platform: state
    to: 'off'
  - entity_id: switch.r2
    platform: state
    to: 'off'
  - entity_id: switch.r3
    platform: state
    to: 'off'
  - entity_id: switch.r4
    platform: state
    to: 'off'
  - entity_id: switch.r5
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.r1
    state: 'off'
  - condition: state
    entity_id: switch.r2
    state: 'off'
  - condition: state
    entity_id: switch.r3
    state: 'off'
  - condition: state
    entity_id: switch.r4
    state: 'off'
  - condition: state
    entity_id: switch.r5
    state: 'off'
  action:
  - data:
      entity_id: switch.relais_pumpe
    service: switch.turn_off

